-- Remove unused original trait modifiers; CSE adds new ones
-- AFAICT these aren't used by anything. Sovereignty uses Leader_XP2
DELETE FROM "ModifierArguments"
WHERE "ModifierId" IN ('MINOR_CIV_SCIENTIFIC_SEND_TRADE_ROUTE_BONUS', 'MINOR_CIV_RELIGIOUS_SEND_TRADE_ROUTE_BONUS', 'MINOR_CIV_TRADE_SEND_TRADE_ROUTE_BONUS', 'MINOR_CIV_CULTURAL_SEND_TRADE_ROUTE_BONUS', 'MINOR_CIV_MILITARISTIC_SEND_TRADE_ROUTE_BONUS', 'MINOR_CIV_INDUSTRIAL_SEND_TRADE_ROUTE_BONUS');

DELETE FROM "Modifiers"
WHERE "ModifierId" IN ('MINOR_CIV_SCIENTIFIC_SEND_TRADE_ROUTE_BONUS', 'MINOR_CIV_RELIGIOUS_SEND_TRADE_ROUTE_BONUS', 'MINOR_CIV_TRADE_SEND_TRADE_ROUTE_BONUS', 'MINOR_CIV_CULTURAL_SEND_TRADE_ROUTE_BONUS', 'MINOR_CIV_MILITARISTIC_SEND_TRADE_ROUTE_BONUS', 'MINOR_CIV_INDUSTRIAL_SEND_TRADE_ROUTE_BONUS');

DELETE FROM "TraitModifiers"
WHERE "ModifierId" IN ('MINOR_CIV_SCIENTIFIC_SEND_TRADE_ROUTE_BONUS', 'MINOR_CIV_RELIGIOUS_SEND_TRADE_ROUTE_BONUS', 'MINOR_CIV_TRADE_SEND_TRADE_ROUTE_BONUS', 'MINOR_CIV_CULTURAL_SEND_TRADE_ROUTE_BONUS', 'MINOR_CIV_MILITARISTIC_SEND_TRADE_ROUTE_BONUS', 'MINOR_CIV_INDUSTRIAL_SEND_TRADE_ROUTE_BONUS');
