--Core\City-State Types\Ethiopia\CSE_Militaristic_Ethiopia.sql
-- Support for More Maritime: Seaside Sectors Arsenal buildings

INSERT INTO "TraitModifiers"
	(	TraitType, 						ModifierId												)
VALUES
	(	'MINOR_CIV_MILITARISTIC_TRAIT',	'MODIFIER_CSE_MILITARISTIC_WAREHOUSE_UNITS_ETHIOPIA'	),
	(	'MINOR_CIV_MILITARISTIC_TRAIT',	'MODIFIER_CSE_MILITARISTIC_DRYDOCK_UNITS_ETHIOPIA'		),
	(	'MINOR_CIV_MILITARISTIC_TRAIT',	'MODIFIER_CSE_MILITARISTIC_NAVALACADEMY_UNITS_ETHIOPIA'	);

INSERT INTO "Modifiers"
	(	"ModifierId",													"ModifierType",											"SubjectRequirementSetId"			)
VALUES	
	(	'MODIFIER_CSE_MILITARISTIC_WAREHOUSE_UNITS_ETHIOPIA',			'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',					'PLAYER_HAS_LARGEST_INFLUENCE'		),
	(	'MODIFIER_CSE_MILITARISTIC_WAREHOUSE_UNITS_MOD_ETHIOPIA',		'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_PRODUCTION_CHANGE',	'REQSET_CSE_CITY_HAS_WAREHOUSE'		),
	(	'MODIFIER_CSE_MILITARISTIC_DRYDOCK_UNITS_ETHIOPIA',				'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',					'PLAYER_HAS_LARGEST_INFLUENCE'		),
	(	'MODIFIER_CSE_MILITARISTIC_DRYDOCK_UNITS_MOD_ETHIOPIA',			'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_PRODUCTION_CHANGE',	'REQSET_CSE_CITY_HAS_DRYDOCK'		),
	(	'MODIFIER_CSE_MILITARISTIC_NAVALACADEMY_UNITS_ETHIOPIA',		'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',					'PLAYER_HAS_LARGEST_INFLUENCE'		),
	(	'MODIFIER_CSE_MILITARISTIC_NAVALACADEMY_UNITS_MOD_ETHIOPIA',	'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_PRODUCTION_CHANGE',	'REQSET_CSE_CITY_HAS_NAVALACADEMY'	);

INSERT INTO "ModifierArguments"
	(	"ModifierId",													"Name",			"Value"														)
VALUES
	(	'MODIFIER_CSE_MILITARISTIC_WAREHOUSE_UNITS_ETHIOPIA',			'ModifierId',	'MODIFIER_CSE_MILITARISTIC_WAREHOUSE_UNITS_MOD_ETHIOPIA'	),
	(	'MODIFIER_CSE_MILITARISTIC_WAREHOUSE_UNITS_MOD_ETHIOPIA',		'Amount',		1															),
	(	'MODIFIER_CSE_MILITARISTIC_DRYDOCK_UNITS_ETHIOPIA',				'ModifierId',	'MODIFIER_CSE_MILITARISTIC_DRYDOCK_UNITS_MOD_ETHIOPIA'		),
	(	'MODIFIER_CSE_MILITARISTIC_DRYDOCK_UNITS_MOD_ETHIOPIA',			'Amount',		1															),
	(	'MODIFIER_CSE_MILITARISTIC_NAVALACADEMY_UNITS_ETHIOPIA',		'ModifierId',	'MODIFIER_CSE_MILITARISTIC_NAVALACADEMY_UNITS_MOD_ETHIOPIA'	),
	(	'MODIFIER_CSE_MILITARISTIC_NAVALACADEMY_UNITS_MOD_ETHIOPIA',	'Amount',		1															);

UPDATE	"ModifierArguments"
SET		"Value" = 1
WHERE	"Name" = 'Amount' AND "ModifierId" = 'MODIFIER_CSE_MILITARISTIC_WAREHOUSE_UNITS_MOD';

UPDATE	"ModifierArguments"
SET		"Value" = 3
WHERE	"Name" = 'Amount' AND "ModifierId" = 'MODIFIER_CSE_MILITARISTIC_NAVALACADEMY_UNITS_MOD';